version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - apartments:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 3001:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  apartments: