version: '3.8'

services:
  app:
    image: omaralhamad/apartments:latest
    ports:
      - "3010:3000"
    secrets:
      - google_credentials
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/run/secrets/google_sheets_credentials"

secrets:
  google_sheets_credentials:
    external: true
